### ISSUE TITLE
Missing ALACEncoder.h

### ISSUE THREAD

**Issue by ralph-irving** [philippe44/libraop#1]
The new alac changes appear to be missing files?

raop_play$ make -f Makefile.x86
cc -Wall -Wno-multichar -Wno-unused-but-set-variable -fPIC -ggdb -O2  -I. -I/usr/include/valgrind/memcheck -I/usr/include/valgrind -I/usr/include/memcheck -I/usr/include/include -I./tools -I../alac -I./src -I./src/inc   -I. -I/usr/include/valgrind/memcheck -I/usr/include/valgrind -I/usr/include/memcheck -I/usr/include/include -I./tools -I../alac -I./src -I./src/inc ./src/alac_wrapper.cpp -c -o bin/x86/alac_wrapper.o
./src/alac_wrapper.cpp:25:25: fatal error: ALACEncoder.h: No such file or directory
compilation terminated.
make: *** [Makefile:41: bin/x86/alac_wrapper.o] Error 1

**Comment by philippe44** [comment]
Crap, you right, I forgot to mention that these are the ALAC files from https://github.com/macosforge/alac

**Comment by ralph-irving** [comment]
Thanks, got it built.
