### ISSUE TITLE
alac or pcm exact format

### ISSUE THREAD

**Issue by NebzHB** [philippe44/libraop#16]
Hello,

I'm trying to send pcm or alac to this player but can't find the right format... it's too fast or just make a white noise

i tried :
```
  ffmpeg -y -i myfile.mp3 -vn -acodec alac -sample_fmt s16p "myfile.m4a";
  ffmpeg -y -i myfile.mp3 -vn -acodec pcm_s16le -f s16le "myfile.pcm";
```

could you help ? i'm trying to recode using ffmpeg (or avconv) what options do you choose ?

**Comment by philippe44** [comment]
you need to use plain pcm, so option 2 is what you need (option 1 should produce white noise). Then make sure that your file is using 44.1kHz sample rate (don't know the ffmpeg options to resample)

**Comment by NebzHB** [comment]
s16le seems to work, but i have to put 88200 rate for that...

or do you know the sox or else option for piping in stdin ?

**Comment by philippe44** [comment]
If you have to use 88200 it means that it’s not a stereo file or something like that. I don’t understand why you want to use sox, ffmpeg can do the job. Then pipe is well documented on this and I think I use - as well in raop_play (I’ve not used it in a while, but the cmd line help will tell you)

**Comment by NebzHB** [comment]
yes it's mono file for most (TTS) , i've seen in your code, you assume it's stereo, could you detect that ?

about sox it was just an idea, ffmpeg is good too

about s16le, do you know if it's the most likely to work format ? my project will be on several archs (x86, x86_64, armhf, arm64, etc)

if you want, i've forked your project and fixed several things for compilation on linux and working with debian buster (including openssl 1.0 because buster install 1.1 and it's not working)

**Comment by philippe44** [comment]
So you have to convert to stereo before sending it to raop_play. I think ffmpeg can do that

**Comment by NebzHB** [comment]
ok for others ppl reading, something like this seems to work fine :
`
ffmpeg -y -i myfile.mp3 -vn -ac 2 -ar 44100 -acodec pcm_s16le -f s16le "myfile.pcm";
`

about s16le, do you know if it's the most likely to work format ? my project will be on several archs (x86, x86_64, armhf, arm64, etc)

if you want, i've forked your project and fixed several things for compilation on linux and working with debian buster (including openssl 1.0 because buster install 1.1 and it's not working)

**Comment by philippe44** [comment]
Yes, pull requests are always welcome. This project is more a reference for the library I’m using in many other projects, hence I did not a lot of updates of the application itself, more on the library. If you look at my other projects, I’ve changed the way I’m using ssl to be able to load any version on any platform

**Comment by philippe44** [comment]
Re 16 bits little endian, the only cpu that can be problem are mips and sparc, afaik, all others are little endian. I have to check how much there are endianness issues, I’ve tried to take care of most of them as what I do is usually cross os and cpu, but I can’t say that I tested a lot of mips and sparc

**Comment by NebzHB** [comment]
in which project do you have solved the ssl ?

**Comment by philippe44** [comment]
LMS-to-UPnP for example

**Comment by NebzHB** [comment]
I'm sorry but I'm not a c dev... and I don't see how you've solved that in those project and how to solve it for this one...
