### ISSUE TITLE
Get volume from airplay device

### ISSUE THREAD

**Issue by NebzHB** [philippe44/libraop#18]
Hello again,

Do you know how could i get the current volume of the airplay device ? (To save it before playing my file and then set it back after playing my file)

Do you know how to set it without playing any file ?

Thank you

**Comment by philippe44** [comment]
You have to use DACP. See what I'm doing in AirConnect for example. It's a bit complicated, unfortunatey.

**Comment by NebzHB** [comment]
Yes too complicated for me...
