### ISSUE TITLE
valgrind repo seems not available anymore

### ISSUE THREAD

**Issue by NebzHB** [philippe44/libraop#21]
Dear,

fatal: unable to access ‘http://repo.or.cz/valgrind.git/ 1’: Recv failure: Connection reset by peer

it seems that repo is not available anymore, do you have any alternative ?

**Comment by NebzHB** [comment]
[submodule "vendor/valgrind"]
	path = vendor/valgrind
	url = http://sourceware.org/git/valgrind.git

seems ok, do you want a PR ? or you update on your local copy

**Comment by philippe44** [comment]
I'm not sure I'm following

**Comment by NebzHB** [comment]
They did changed their repo, but then change it back, may be closed
