### ISSUE TITLE
aarch64 issue?

### ISSUE THREAD

**Issue by nadigo** [philippe44/libraop#27]
see the error on RPI 4 64 bit

```
uname -a 
Linux phono 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux
```

```
pi@phono:~/RAOP-Player/build $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/10/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 


```

> [  3%] Building C object CMakeFiles/raop_play.dir/tools/log_util.c.o
In file included from /home/pi/RAOP-Player/tools/log_util.c:28:
/home/pi/RAOP-Player/tools/platform.h:130:15: error: conflicting types for ‘__u64’
  130 | typedef u64_t __u64;
      |               ^~~~~
In file included from /usr/include/asm-generic/types.h:7,
                 from /usr/include/aarch64-linux-gnu/asm/types.h:1,
                 from /usr/include/linux/types.h:5,
                 from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:22,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:30,
                 from /usr/include/signal.h:291,
                 from /home/pi/RAOP-Player/tools/platform.h:49,
                 from /home/pi/RAOP-Player/tools/log_util.c:28:
/usr/include/asm-generic/int-ll64.h:31:42: note: previous declaration of ‘__u64’ was here
   31 | __extension__ typedef unsigned long long __u64;
      |                                          ^~~~~
In file included from /home/pi/RAOP-Player/tools/log_util.c:28:
/home/pi/RAOP-Player/tools/platform.h:133:15: error: conflicting types for ‘__s64’
  133 | typedef s64_t __s64;
      |               ^~~~~
In file included from /usr/include/asm-generic/types.h:7,
                 from /usr/include/aarch64-linux-gnu/asm/types.h:1,
                 from /usr/include/linux/types.h:5,
                 from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:22,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:30,
                 from /usr/include/signal.h:291,
                 from /home/pi/RAOP-Player/tools/platform.h:49,
                 from /home/pi/RAOP-Player/tools/log_util.c:28:
/usr/include/asm-generic/int-ll64.h:30:44: note: previous declaration of ‘__s64’ was here
   30 | __extension__ typedef __signed__ long long __s64;
      |                                            ^~~~~
make[2]: *** [CMakeFiles/raop_play.dir/build.make:82: CMakeFiles/raop_play.dir/tools/log_util.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/raop_play.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by philippe44** [comment]
I've updated it for aarch64. Please note that this is not a project that I support anymore, so it might or not work

**Comment by nadigo** [comment]
the update doesn't fetch  all of the submodules in .gitmodules (only alac)

fixed:
- `'/home/pi/RAOP-Player/vendor/valgrind/memcheck/memcheck.h:72:10: fatal error: valgrind.h: `
   missing valgrind.h in memcheck folder (valgrind issue ?) - fixed by manually coping the  `valgrind.h` file 
-  `CMakeFiles/raop_play.dir/src/raop_client.c.o: undefined reference to symbol 'pthread_create@@GLIBC_2.17'` which was couldn't be solved by changing LDFLAGS in Makefile.armhf from `-lpthread` to `-pthread `so I manually added `-pthread` in  CMakeCache.txt 
```CMakeCache.txt 
//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-pthread
```
-  copying the new tools/platform.h and src/raop_play.c from the aarch64 commit


After these changes, this [aarch64](https://github.com/nadigo/RAOP-Player/tree/aarch64) fork compiles well of the new 10-30-21 64bit raspberry OS (Debian bullseye)

**Comment by nadigo** [comment]
will compile on RPI4 with [raspi OS arm64](https://downloads.raspberrypi.org/raspios_arm64/images/)

- manually adding missing submodule folders `valgrind @ d7d8231` `curve25519 @ 990f3bf` in /vendor
- manually adding `-pthread` in CMakeCache.txt
`CMAKE_CXX_FLAGS:STRING=-pthread`

below are the 'concerning' warnings I get (playtime integer type?)

> ..
> /home/pi/RAOP-Player/src/raop_play.c: In function ‘main’:
> /home/pi/RAOP-Player/src/raop_play.c:413:42: warning: passing argument 4 of ‘raopcl_send_chunk’ from incompatible pointer type [-Wincompatible-pointer-types]
>   413 |    raopcl_send_chunk(raopcl, buf, n / 4, &playtime);
>       |                                          ^~~~~~~~~
>       |                                          |
>       |                                          __u64 * {aka long long unsigned int *}
> In file included from /home/pi/RAOP-Player/src/raop_play.c:41:
> /home/pi/RAOP-Player/src/raop_client.h:163:75: note: expected ‘u64_t *’ {aka ‘long unsigned int *’} but argument is of type ‘__u64 *’ {aka ‘long long unsigned int *’}
>   163 | bool raopcl_send_chunk(struct raopcl_s *p, u8_t *sample, int size, u64_t *playtime);
>       |                                                                    ~~~~~~~^~~~~~~~
> [100%] Linking CXX executable raop_play
> [100%] Built target raop_play
