### ISSUE TITLE
tools/log_util.c cannot find source file

### ISSUE THREAD

**Issue by NebzHB** [philippe44/libraop#30]
Hi,

when i cmake the project, i get this error : 

```
cmake ..
-- Configuring done
CMake Error at CMakeLists.txt:20 (add_executable):
  Cannot find source file:

    tools/log_util.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:20 (add_executable):
  No SOURCES given to target: raop_play


CMake Generate step failed.  Build files cannot be regenerated correctly.
```
BR's
Nebz

**Comment by NebzHB** [comment]
Then if i remove it from CMakeLists.txt, i have another file : 
```
 cmake ..
-- Configuring done
CMake Error at CMakeLists.txt:19 (add_executable):
  Cannot find source file:

    src/aexcl_lib.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:19 (add_executable):
  No SOURCES given to target: raop_play


CMake Generate step failed.  Build files cannot be regenerated correctly.

```

**Comment by NebzHB** [comment]
then  src/alac_wrapper.cpp

**Comment by NebzHB** [comment]
then libraop/vendor/curve25519/source/curve25519_dh.c (vendor doesn't exists anymore)

**Comment by philippe44** [comment]
You might not have pulled au modules

**Comment by NebzHB** [comment]
as described in readme, i've done : `git submodule update --force --recursive --init --remote`

**Comment by philippe44** [comment]
oh, it's a very old cmake file that I never care to update. I'll clean that

**Comment by philippe44** [comment]
Should be (kind of) working now. CMake made me waste a few hours, as usual

**Comment by NebzHB** [comment]
thank you, i check tonight

**Comment by NebzHB** [comment]
```
cmake ..
CMake Error at CMakeLists.txt:15 (cmake_path):
  Unknown CMake command "cmake_path".


-- Configuring incomplete, errors occurred!

```

it seems that cmake_path comes with cmake 3.20, but latest debian 11 uses 3.18.4 ...

**Comment by philippe44** [comment]
You can easily fix/change that part for your needs or upgrade your cmake

**Comment by NebzHB** [comment]
mmm I use the lib in a plugin for a french domotic software... so it's installed on 100 systems... from raspberry 4 to x86_64... i will use the binaries in /bin then... i've tested the _arm with arm7l and it's working

**Comment by NebzHB** [comment]
thank you.

do you encounter a ~10sec delay when playing to homepods since the latest homepod update too ?

**Comment by philippe44** [comment]
I don't have a homepod
