### ISSUE TITLE
Question about pair-pin-start protocolc

### ISSUE THREAD

**Issue by fduncanh** [philippe44/libraop#32]
Hi

I hope you dont mind  me asking for any advice.

I am a maintainer of the AirPlay (mirror and Audio-streaming) server UxPlay http://github.com/FDH2/UxPlay which
acts like an AppleTV.    Its codebase is C and derives from ShairPlay/AirPlayServer/RpiPlay.  

UxPlay   handles legacy pairing, but this is now off by default  and the Features bit for this and password is turned off. With these features enabled the client initiates pair-pin-start etc.  and when clients are managed with MDM they may request pair-pin-start even if the server does not require a password.So I am considering adding it, but it has never been in the ancestral codebase of [ShairPlay](http:https://github.com/juhovh/shairplay) from which our implementation derives.

* Am I right that your codebase is only implementing it for the client but not the server?

* will I find enough information in you codebase to handle the (C implementation )  of pair-setup-pin on the server before pair verify?

Grateful for any suggestions.

Uxplay  with the features  bit (27) for "supports legacy pairing" turned on currently just does:

pair_setup
pair_verify 1
pair_verify 2
fp_setup

etc

I suppose that pair-pin-setup replaces  pair-setup ?

@fduncanh

**Comment by philippe44** [comment]
Hi - no worries, happy to help if I can. AFAIK, pair-pin-setup is what is used now, I've never implement legacy pairing. 

- my code base is indeed for the client, not for the server
- I think you'll have what you need for a server implementation but I also wrote a doc thht will avoid reverse ingineering the code https://htmlpreview.github.io/?https://github.com/philippe44/RAOP-Player/blob/master/doc/auth_protocol.html

**Comment by fduncanh** [comment]
@philippe44 
thanks!

**Comment by fduncanh** [comment]
@philippe44 

Please can I get some  more advice, specifically about the 256-byte PK (public key).

The Airplay "legacy pairing" codebase that the  [UxPlay](https://github.com/FDH2/UxPlay) server app which I maintain is based on has all the needed features for pairing without a pin, and uses a 32-byte private and 32-byte public ED25519 keypair.   

 Using your work as a guide to try to implement pairing with a pin I have so far got an iOS client to send a pair-pin-start POST request followed by a pair-setup-pin POST request with client_id and method "pin", to which the server replies by showing a pin, and sending a (32 byte) Public key and 16 byte salt.   The client does reply with a 256 byte pk, and a 20 byte proof.

Your guide says `The SRP6 public key corresponding to <a> (A = g ^<a> % N).
Should be calculated by the SRP library`  (where ``<a>`` is the client 32 bytes, private key).

Do you think the server and client can pair with different-size PK keys?   or can one generate a 256-byte PK from a 32 byte ED25519 private key? (using SRP6a?)
