### ISSUE TITLE
Audio cuts out after ~3 minutes when streaming to HomePod

### ISSUE THREAD

**Issue by LinusU** [philippe44/libraop#8]
When streaming to a HomePod, the audio cuts out after about 3 minutes of playback. The `raop_player` binary keeps logging that the audio is being played, with one line printed every second; but the HomePod switches to "Not Playing".

When streaming to an AirPort Express, everything works as expected.

@philippe44 if you have any tips on how to debug/investigate this issue I would be happy to hear them! ❤️

**Comment by philippe44** [comment]
I think I remember that HomePod wants metadata to be sent.

**Comment by philippe44** [comment]
Did it solve the issue? Maybe we can close the issue then

**Comment by LinusU** [comment]
Sorry, I haven't had time to test this yet 🙈 

Will try and get to it this week, otherwise we can close it and I'll just reopen it when I get to further investigating it 👍

**Comment by LinusU** [comment]
Sending keepalive packets (with the function in your last commit) every ~30 seconds fixes the problem and lets me play continuously on the HomePod 🙌 

https://github.com/LinusU/rust-raop-player/commit/d85dc13689f8dfe22d5d2341a6b9378377a27021

Let me know if you want me to make a pull request with a similar change to `raop_play.c` ☺️

**Comment by LinusU** [comment]
For the record, just sending the `mikd 2` metadata (`item_kind = audio`) and no keepalives is not enough to keep the HomePod from cutting out...

edit: neither is sending item_kind, item_name, song_artist & song_album
